url: https://blog.domfarolino.com   # with the https protocol
enforce_ssl: www.blog.domfarolino.com   # without any protoc

# Name of your site (displayed in the header)
name: Dominic Farolino

# Pagination settings
paginate: 5
paginate_path: '/page:num'

# Short bio or description (displayed in the header)
description: Web Developer and Programmer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars2.githubusercontent.com/u/9669289?v=3&s=460

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: domfarolino@gmail.com
  github: domfarolino
  instagram: domfarolino
  linkedin: domfarolino
  twitter: domfarolino
  stackoverflow: users/3947332/dom-farolino
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: +DomFarolino


# Enter your Disqus shortname (not your username) to enable commenting on posts
disqus: domfarolino

google_analytics: UA-88460462-1

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: rouge
permalink: /:title/

tag_page: '/tags/'
category_page: '/categories/'

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
