url: https://blog.domfarolino.com
enforce_ssl: www.blog.domfarolino.com

name: Dominic Farolino
description: Web Developer and Programmer
google_analytics: UA-88460462-1
avatar: https://avatars2.githubusercontent.com/u/9669289?v=3&s=460
disqus: domfarolino # shortname

footer-links: # optional
  email: domfarolino@gmail.com
  github: domfarolino
  instagram: domfarolino
  linkedin: domfarolino
  twitter: domfarolino
  stackoverflow: users/3947332/dom-farolino
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: +DomFarolino

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

# Pagination settings
paginate: 5
paginate_path: '/page:num'

markdown: redcarpet
highlighter: rouge
permalink: /:title/

tag_page: '/tags/'
category_page: '/categories/'

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # | :compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
